### PR TITLE
updated vitepress to latest version

### PR DESCRIPTION
**Pull request by pritamgupta-07**
updated vitepress to latest version ^1.0.0-rc.20  #11

### CODE REVIEW

**Comment by Animeshz** [comment]
Have you verified the changes? It doesn't look like `pnpm-lock.yaml` file has been updated. Can you please execute `pnpm i` push the commit?

**Comment by pritamgupta-07** [comment]
Sorry, I don't have much idea about YAML files. Can you guide me? Actually i am new to this.

**Comment by Animeshz** [comment]
Lock files don't have to be touched by hand, just run `pnpm i`, it'll update by itself :)

**Comment by pritamgupta-07** [comment]
i meshed up while installing pnpm on my machine.

**Comment by pritamgupta-07** [comment]
i think everything is okay this time.

**Comment by Animeshz** [comment]
Last commit is again incompatible with lock file (you changed the `package.json` without running `pnpm i`). Please run `pnpm i` and push again. This will be the last nitpick before merging.

Next to it, everything else LGTM :tada:, thanks for your contribution!

**Comment by pritamgupta-07** [comment]
So i need to run pnpm i everytime when ever package.json file is changes.  thanks for the guidance.

**Pull request merged**
